spring.application.name=crm


# Conexión MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/metehora_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true